name: Deploy Musicbot
run-name: ${{ gitea.actor }} is deploying ${{ vars.repository }}
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get highest tag
        id: get_highest_tag
        run: |
          # Get all tags, sort them, and get the highest tag
          highest_tag=$(git tag | sort -V | tail -n 1)
          # Remove the 'v' prefix and set the VERSION environment variable
          echo "VERSION=${highest_tag#v}" >> $GITHUB_ENV
          echo "Highest tag is: $highest_tag"
      
      - name: Login to Gitea Registry
        run: echo "${{ secrets.REGISTRY_PAT }}" | docker login ${{ vars.URL }} -u ${{ secrets.REGISTRY_USER }} --password-stdin

      - name: Build image
        run: docker build --build-arg VERSION=${{ env.VERSION }} -t ${{ vars.URL }}/${{ vars.repository }}:latest .

      - name: Push image
        run: docker push ${{ vars.URL }}/${{ vars.repository }}:latest