name: Deploy Musicbot
run-name: ${{ gitea.actor }} is deploying ${{ vars.repository }}
on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker version
        run: echo "VERSION=${GITHUB_REF}" 

      - name: Login to Gitea Registry
        run: echo "${{ secrets.REGISTRY_PAT }}" | docker login ${{ vars.URL }} -u ${{ secrets.REGISTRY_USER }} --password-stdin

      - name: Build image
        run: docker build -t ${{ vars.URL }}/${{ vars.repository }}:{GITEA_TAG}.

      - name: Push image
        run: docker push ${{ vars.URL }}/${{ vars.repository }}:{GITEA_TAG}
