name: Deploy Musicbot
run-name: ${{ gitea.actor }} is deploying ${{ vars.repository }}
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Gitea Registry
        run: echo "${{ secrets.REGISTRY_PAT }}" | docker login ${{ vars.URL }} -u ${{ secrets.REGISTRY_USER }} --password-stdin

      - name: Build image
        run: docker build -t ${{ vars.URL }}/${{ vars.repository }}/jmusicbot:latest .

      - name: Push image
        run: docker push ${{ vars.URL }}/${{ vars.repository }}/jmusicbot:latest

      - name: Connect Docker Image to Gitea Repo
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.REGISTRY_PAT }}" \
            -H "Content-Type: application/json" \
            -d '{"name":"musicbot","image":"'"${{ vars.URL }}/${{ vars.repository }}:latest"'"}' \
            ${{ vars.URL }}/api/v1/repos/${{ vars.repository }}/containers
